RECOMMENDATIONS_CATALOG_NAME: str = "Top Picks For You"
DEFAULT_MIN_ITEMS: int = 8
DEFAULT_CATALOG_LIMIT = 20

DEFAULT_CONCURRENCY_LIMIT: int = 30


DEFAULT_MINIMUM_RATING_FOR_THEME_BASED_MOVIE: float = 7.2
DEFAULT_MINIMUM_RATING_FOR_THEME_BASED_TV: float = 6.8
